name: deploy treebank

on:
  push:
    branches-ignore:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        apt install -y poppler-utils pdflatex
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: update treebank
      run: |
        python generate_treebank.py
    - name: update plots
      run: |
        python generate_plots.py
    - name: update tree renderings 
      run: |
        python generate_treeplots.py
    - name: deploy treebank
      uses: peaceiris/actions-gh-pages@v2.5.1
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./public
      with:
        keepFiles: true
        
        
        
        
#     - name: state and commit treebank update
#       run: |
#         git config --global user.email "daniel.harasim@epfl.ch"
#         git config --global user.name "dharasim"
#         git add treebank.json
#         git commit -m "automatically update treebank from annotations"
#     - name: push treebank update
#       run: |
#         git status
#         git push --set-upstream origin master
