name: generate treebank file

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: generate treebank
      run: |
        python generate_treebank.py
    - name: push treebank
      uses: ludeeus/action-push@0.0.1
      env:
        ACTION_MAIL: "daniel.harasim@epfl.ch"
        ACTION_NAME: Daniel Harasim
        ACTION_BRANCH: master
        ACTION_MESSAGE: update treebank
        ACTION_DEPLOY_KEY: ${{ secrets.ACTION_DEPLOY_KEY }}
