name: generate treebank file

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: update treebank
      run: |
        python generate_treebank.py
    - name: state and commit treebank update
      run: |
        git config --global user.email "daniel.harasim@epfl.ch"
        git config --global user.name "dharasim"
        git add treebank.json
        git commit -m "automatically update treebank from annotations"
    - name: push treebank update
      run: |
        git push
        


#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
